# Site settings
title: "Prabhat Tiwari"
description: "Prabhat's personal website and resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Prabhat Tiwari"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "prabhat_twr@rediffmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+91 8530736633"
resume_contact_address:         "Varanasi, Uttar Pradesh, India"

resume_header_contact_info:     "Varanasi, Uttar Pradesh, India • +91 85307366333 • prabhat_twr@rediffmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>A highly motivated individual with a Master of Science degree in Artificial Intelligence from the University of Aberdeen, certified as a Tensorflow Developer, specializing in machine learning, data mining, and natural language processing. With hands-on experience in developing AI solutions, a strong passion exists for leveraging technology for positive societal impact. The goal is to driving innovation and contributing to positive change.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/astro-wizard/"
  resume_twitter_url:           "http://twitter.com/astro_wizard_"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  #resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://joelglovier.com"
  #resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
